### ISSUE TITLE
Minimize() and Maximize() prompt "illegal operation"

### ISSUE THREAD

**Issue by noahjussila** [cvxgrp/CVXR#107] opened 2022-07-08 14:55 UTC
**Describe the bug** 

When calling `Minimize()` and `Maximize()`, I get an error code about an illegal operation. 

**To Reproduce** 

```
x <- Variable(1)
y <- Variable(1)
objective <- Minimize(x^2 + y^2)
```

**Expected behavior**

**Output**

```
 *** caught illegal operation ***
address 0x12a831b11, cause 'illegal opcode'

Traceback:
 1: gmp::as.bigq(p)
 2: pow_high(p)
 3: .local(.Object, ...)
 4: initialize(value, ...)
 5: initialize(value, ...)
 6: new("Power", ...)
 7: .Power(x = x, p = p, max_denom = max_denom)
 8: Power(x = e1, p = e2)
 9: x^2
10: x^2
11: .local(.Object, ...)
12: initialize(value, ...)
13: initialize(value, ...)
14: new("Minimize", ...)
15: .Minimize(expr = expr)
16: Minimize(x^2 + y^2)
```

**Version**
```
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] CVXR_1.0-10

loaded via a namespace (and not attached):
 [1] bit_4.0.4       compiler_4.2.1  R6_2.5.1        Matrix_1.4-1    gmp_0.6-5       Rcpp_1.0.8.3    bit64_4.0.5     grid_4.2.1      Rmpfr_0.8-9     lattice_0.20-45
```

**Additional context**

When run in RStudio, the session crashes without displaying any output. It seems linked to this [issue](https://forgemia.inra.fr/sylvain.jasson/gmp/-/issues/1)

**Comment by bnaras** [comment] 2022-07-08 17:16
Sorry, can't reproduce at all.

```
> x <- Variable(1)
> y <- Variable(1)
> objective <- Minimize(x^2 + y^2)
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin21.5.0 (64-bit)
Running under: macOS Monterey 12.4

Matrix products: default
BLAS:   /usr/local/Cellar/openblas/0.3.20/lib/libopenblasp-r0.3.20.dylib
LAPACK: /usr/local/Cellar/r/4.2.1/lib/R/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] CVXR_1.0-10

loaded via a namespace (and not attached):
 [1] bit_4.0.4       compiler_4.2.1  R6_2.5.1        Matrix_1.4-1   
 [5] gmp_0.6-5       Rcpp_1.0.8.3    bit64_4.0.5     grid_4.2.1     
 [9] Rmpfr_0.8-9     lattice_0.20-45
```

**Comment by bnaras** [comment] 2022-10-27 22:44
Closing because not reproducible.

**Closed** 2022-10-27 22:43 UTC
