### ISSUE TITLE
CVXR affects random number generation

### ISSUE THREAD

**Issue by EugeneAtl** [cvxgrp/CVXR#89] opened 2020-11-09 21:57 UTC
I noticed that random number generation would be affected after running CVXR. I tried a few different solvers including ECOS and SCS, and all had that issue. Is it the case that they all use stochastic algorithms? Is there any deterministic solver available? Thanks!

**Comment by bnaras** [comment] 2022-01-12 18:00
Closing due to lack of a reproducible example relevant to the issue.

**Closed by bnaras** 2022-01-12 18:00 UTC
